### PR TITLE
corrected path for run_web.sh in docker-compose.yml and set HOST do d…

### PR DESCRIPTION
**Pull request by hbutau**
…b in settings.py

### CODE REVIEW

**Comment by hbutau** [comment]
We need to set the HOST to 'db' instead of '127.0.0.1' so that we can connect to running postgres.

**Comment by shakedown-street** [comment]
Thanks for this, one question though, is there any reason for adding `psycopg2` into installed apps?  As far as I'm aware only Django apps need to be put in there.  If I'm wrong let me know your reasoning, if not can you take that out and commit again?

**Comment by hbutau** [comment]
Oops thank you very much you are right, I had meant to put it into requirements and had missed that it was in requirements already. I will recommit and also fix 'run-web.sh' which was giving this error: `db_1   | 
db_1   | waiting for server to start....2018-02-25 16:52:43.245 UTC [38] LOG:  listening on IPv4 address "127.0.0.1", port 5432
web_1  | /webapps/run_web.sh: line 3: cd: punkweb-boards/: No such file or directory
db_1   | 2018-02-25 16:52:43.245 UTC [38] LOG:  could not bind IPv6 address "::1": Cannot assign requested address`
since we are in /webapps already when the container is started.

**Comment by shakedown-street** [comment]
Thanks again for your contribution!

By the way, I'm currently working on a comprehensive list of features to add, so that contributors can pick features they want to take a crack at building for all of us to benefit off of.  I'll add it in tonight, incase you're interested in contributing any features :)

**Comment by hbutau** [comment]
Thank you also for accepting my contribution. I am still browsing to get a full understanding of punkweb boards. I  am intrested in contributing with and working on  any new features.

**Comment by hbutau** [comment]
Hi @shakedown-street , did you manage to add the list you refered to above? :point_up:

**Comment by shakedown-street** [comment]
@hbutau Hey sorry, I haven't had a chance to work on the list at all, I've been pretty busy with work.  Hopefully in the next few days I'll have a list ready.

**Pull request merged**
